version: '3.8'

services:
  node:
    image: vaibhavrajnathchauhan/product-management:2
    container_name: PIM
    ports:
      - 3004:3004
    env_file:
      - .env
    depends_on:
      - redis
    
  redis:
    image: redis
    ports:
      - 6379:6379
  