---
- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
    
  tasks:
  - name: Updating the current compose file
    replace:
      path: /home/ec2-user/tanu/docker-compose.yml
      regexp: 'vaibhavrajnathchauhan\/product-management:*(.+)$'
      replace: "vaibhavrajnathchauhan/product-management:{{ BUILD_ID }}"

  # docker compose up
  - name: Running the container
    docker_compose:
      project_src: /home/ec2-user/tanu
      build: false
      restarted: true